import { signalRepo } from './kernelService';
import { getProjectRoster } from './projectService';
import { formatChoice } from '../kernel/domain/Timeline';

/**
 * Generates a structured Alignment Report from the immutable signal ledger.
 * Gated behind the `isolyne_export` RevenueCat entitlement ($2.99 one-time).
 */
export async function generateAlignmentReport(squadId: string, projectName: string = 'Active Project'): Promise<string> {
  const signals = await signalRepo.getBySquad(squadId);
  const roster = await getProjectRoster(squadId, 'Alice');

  const now = new Date();
  let report = `# 🎯 Isolyne Alignment Report\n\n`;
  report += `**Project:** ${projectName}\n`;
  report += `**Generated:** ${now.toLocaleDateString()} ${now.toLocaleTimeString()}\n`;
  report += `**Squad:** ${roster.join(', ')}\n\n`;
  report += `---\n\n`;
  report += `## 📜 Chronological Decision Ledger\n\n`;

  if (signals.length === 0) {
    report += `_No signals recorded yet. Start by stating a decision in the channel._\n`;
    return report;
  }

  // Chronological order
  const sorted = [...signals].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  let gapCount = 0;
  let resolutionCount = 0;
  let decisionCount = 0;

  for (const s of sorted) {
    const d = new Date(s.timestamp);
    const ts = `${d.toLocaleDateString([], { month: 'short', day: 'numeric' })} ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;

    switch (s.type) {
      case 'decision_stated': {
        decisionCount++;
        const topic = s.payload?.topic || 'General';
        const choice = s.payload?.choice ? formatChoice(s.payload.choice) : 'Unknown';
        report += `- **[${ts}]** 📌 @${s.actorId} → **${topic}**: "${choice}"\n`;
        if (s.payload?.verbatim) {
          report += `  > _"${s.payload.verbatim}"_\n`;
        }
        break;
      }
      case 'divergence_detected': {
        gapCount++;
        const gapType = s.payload?.gapType?.replace(/_/g, ' ')?.toUpperCase() || 'GAP';
        report += `- **[${ts}]** ⚠️ **${gapType}** on ${s.payload?.topic || 'General'}\n`;
        break;
      }
      case 'alignment_agree': {
        resolutionCount++;
        const topic = s.payload?.topic || 'General';
        const choice = s.payload?.choice ? formatChoice(s.payload.choice) : '';
        report += `- **[${ts}]** 🤝 @${s.actorId} aligned → **${topic}**${choice ? `: "${choice}"` : ''}\n`;
        break;
      }
      case 'member_joined': {
        report += `- **[${ts}]** 👤 @${s.actorId} joined the squad\n`;
        break;
      }
      case 'alignment_challenge': {
        report += `- **[${ts}]** 🔄 @${s.actorId} challenged the proposal on **${s.payload?.topic || 'General'}**\n`;
        break;
      }
    }
  }

  report += `\n---\n\n`;
  report += `## 📊 Session Summary\n\n`;
  report += `| Metric | Count |\n`;
  report += `|--------|-------|\n`;
  report += `| Decisions Stated | ${decisionCount} |\n`;
  report += `| Silent Drifts Caught | ${gapCount} |\n`;
  report += `| Alignments Reached | ${resolutionCount} |\n`;
  report += `| Squad Members | ${roster.length} |\n`;
  report += `| Total Signals | ${sorted.length} |\n\n`;

  report += `---\n\n`;
  report += `_Generated by Isolyne Pro · The disagreement detector for teams that move too fast to argue._\n`;
  return report;
}
